/* JTT sport config — NFL. Loaded by the unified shell as window.SPORT_CONFIG. */
window.SPORT_CONFIG = {
  // official team logos — ESPN CDN by lowercase abbreviation (onerror falls back to the jersey)
  logoCdn: 'https://a.espncdn.com/i/teamlogos/nfl/500/', logoCdnExt: '.png', teamIds: { LA:'lar', WAS:'wsh' },
  key: 'nfl',
  name: 'NFL',
  jupiter: {
    markets: [['passYds','Pass Yd'],['rushYds','Rush Yd'],['recYds','Rec Yd'],['receptions','Rec'],['rushAtt','Rush Att'],['passTds','Pass TD'],['tackles','Tackles']],
    mlab:    { passYds:'pass yd', rushYds:'rush yd', recYds:'rec yd', receptions:'rec', rushAtt:'rush att', passTds:'pass TD', tackles:'tackles' },
    base:    { passYds:225, rushYds:45, recYds:45, receptions:4, rushAtt:12, passTds:1.5, tackles:6 },
  },
  mktNames: { passYds:'Pass Yds', passAtt:'Pass Att', passTds:'Pass TDs', rushYds:'Rush Yds', rushAtt:'Rush Att', receptions:'Receptions', recYds:'Rec Yds', rushRecYds:'Rush+Rec Yds', anytimeTd:'Anytime TD', tackles:'Tackles+Ast' },
  pcStats:  [['passYds','PaYds'],['passAtt','PaAtt'],['passTds','PaTD'],['rushYds','RuYds'],['rushAtt','Car'],['receptions','Rec'],['recYds','ReYds'],['rushRecYds','R+R'],['anytimeTd','ATD'],['fanPts','FanPts'],['longRec','LngRec'],['longRush','LngRsh'],['longComp','LngCmp'],['tackles','Tk+A'],['soloTk','Solo']],
  cmbPick:  [['passYds','Pass Yds',180],['rushYds','Rush Yds',40],['recYds','Rec Yds',40],['receptions','Receptions',3],['rushAtt','Rush Att',10],['passTds','Pass TDs',1.2],['anytimeTd','Anytime TD',0.35],['tackles','Tackles+Ast',6]],
  fxpMarkets: [['passYds','Pass Yd'],['rushYds','Rush Yd'],['recYds','Rec Yd'],['receptions','Rec'],['rushAtt','Rush Att'],['passTds','Pass TD'],['tackles','Tackles']],
  dvpsOpts: [['receptions','Receptions'],['recYds','Rec Yds'],['recTds','Rec TDs'],['rushYds','Rush Yds'],['rushAtt','Rush Att'],['rushTds','Rush TDs'],['passYds','Pass Yds'],['passTds','Pass TDs'],['anytimeTd','Anytime TD'],['fanPts','Fan Pts'],['tackles','Tackles+Ast']],
  eliteDefs: [['passYds','Pass Yds'],['passAtt','Pass Att'],['passTds','Pass TDs'],['passInt','INTs'],['recYds','Rec Yds'],['rushYds','Rush Yds'],['receptions','Receptions']],
  dvpStylePos: {'Dual Threat':'QB','Gunslinger':'QB','Game Manager':'QB','Pocket Passer':'QB','Workhorse':'RB','Committee Back':'RB','Receiving Back':'RB','Goal-Line Back':'RB','Alpha WR':'WR','Deep Threat':'WR','Possession / Slot':'WR','Rotational WR':'WR','Route TE':'TE','Hybrid TE':'TE','Blocking TE':'TE','TD Machine':'All Positions','Volume King':'All Positions','Fantasy Stars':'All Positions'},
  h2hKeys: [['points','Points'],['passYds','Pass Yds'],['rushYds','Rush Yds'],['passTds','Pass TDs'],['rushTds','Rush TDs'],['receptions','Receptions'],['passInt','INTs Thrown'],['sacks','Sacks Taken']],
  lowCount: ['passTds','rushTds','recTds','anytimeTd','passInt','totalTds'],
  dvpByPos: true,
  display: [['fanPts','FP'],['passYds','PaYd'],['rushYds','RuYd'],['recYds','ReYd'],['rushRecYds','R+R'],['receptions','Rec'],['totalTds','TDs'],['snapPct','Snap%']],
  displaySets: { All:[['fanPts','FP'],['passYds','PaYd'],['rushYds','RuYd'],['recYds','ReYd'],['rushRecYds','R+R'],['receptions','Rec'],['totalTds','TDs'],['snapPct','Snap%']], QB:[['passYds','PaYd'],['passAtt','Att'],['passComp','Cmp'],['passTds','PaTD'],['passInt','INT'],['rushYds','RuYd'],['rushAtt','Car'],['rushTds','RuTD'],['fanPts','FP'],['snapPct','Snap%']], RB:[['rushYds','RuYd'],['rushAtt','Car'],['ypc','YPC'],['rushTds','RuTD'],['glCarry','GL'],['receptions','Rec'],['targets','Tgt'],['recYds','ReYd'],['rushRecYds','R+R'],['fanPts','FP'],['snapPct','Snap%']], WR:[['receptions','Rec'],['targets','Tgt'],['tgtShare','Tgt%'],['recYds','ReYd'],['ypr','YPR'],['aDot','aDOT'],['recTds','ReTD'],['rzTgt','RZ'],['rushRecYds','R+R'],['fanPts','FP'],['snapPct','Snap%']], TE:[['receptions','Rec'],['targets','Tgt'],['tgtShare','Tgt%'],['recYds','ReYd'],['ypr','YPR'],['aDot','aDOT'],['recTds','ReTD'],['rzTgt','RZ'],['rushRecYds','R+R'],['fanPts','FP'],['snapPct','Snap%']], LB:[['tackles','Tk+A'],['soloTk','Solo'],['astTk','Ast'],['tfl','TFL'],['defSacks','Sack'],['snapPct','Snap%']], DL:[['tackles','Tk+A'],['soloTk','Solo'],['astTk','Ast'],['tfl','TFL'],['defSacks','Sack'],['snapPct','Snap%']], DB:[['tackles','Tk+A'],['soloTk','Solo'],['astTk','Ast'],['tfl','TFL'],['defSacks','Sack'],['snapPct','Snap%']] },
  multiMkts: [['passYds','Pass Yds'],['rushYds','Rush Yds'],['recYds','Rec Yds'],['receptions','Receptions'],['rushAtt','Rush Att'],['passAtt','Pass Att'],['rushRecYds','Rush+Rec'],['anytimeTd','Anytime TD'],['tackles','Tackles+Ast']],
  nerdMkts: [['passYds','Pass Yds'],['recYds','Rec Yds'],['rushYds','Rush Yds'],['receptions','Receptions'],['rushAtt','Rush Att'],['passAtt','Pass Att'],['rushRecYds','Rush+Rec'],['tackles','Tackles+Ast']],
  settingsMkts: [['passYds','Pass Yds'],['rushYds','Rush Yds'],['recYds','Rec Yds'],['receptions','Receptions'],['rushAtt','Rush Att'],['passTds','Pass TDs'],['anytimeTd','Anytime TD'],['tackles','Tackles+Ast']],
  compareStats: [['passYds','Pass Yds'],['rushYds','Rush Yds'],['recYds','Rec Yds'],['receptions','Receptions'],['rushAtt','Rush Att'],['fanPts','Fan Pts'],['tackles','Tackles+Ast']],
  boxCols: [['passYds','PaYd'],['rushYds','RuYd'],['recYds','ReYd'],['receptions','Rec'],['rushRecYds','R+R'],['totalTds','TD']],
  cmpAliases: {'passing yards':'passYds','pass yards':'passYds','pass yds':'passYds','passyds':'passYds','py':'passYds','passing tds':'passTds','pass tds':'passTds','pass td':'passTds','passing touchdowns':'passTds','pass touchdowns':'passTds','pass attempts':'passAtt','pass att':'passAtt','attempts':'passAtt','completions':'passComp','pass completions':'passComp','comp':'passComp','interceptions':'passInt','ints':'passInt','int':'passInt','picks':'passInt','rushing yards':'rushYds','rush yards':'rushYds','rush yds':'rushYds','rushyds':'rushYds','rush attempts':'rushAtt','carries':'rushAtt','rush att':'rushAtt','rushing tds':'rushTds','rush tds':'rushTds','rush td':'rushTds','receiving yards':'recYds','rec yards':'recYds','rec yds':'recYds','recyds':'recYds','receptions':'receptions','reception':'receptions','catches':'receptions','rec':'receptions','receiving tds':'recTds','rec tds':'recTds','rec td':'recTds','rush rec yards':'rushRecYds','rush+rec yards':'rushRecYds','rush+rec':'rushRecYds','rush rec':'rushRecYds','scrimmage yards':'rushRecYds','anytime td':'anytimeTd','anytime touchdown':'anytimeTd','atd':'anytimeTd','touchdown':'anytimeTd','td':'anytimeTd','targets':'targets','target':'targets','longest reception':'longRec','long rec':'longRec','longest catch':'longRec','longest rush':'longRush','long rush':'longRush','longest run':'longRush','longest completion':'longComp','long comp':'longComp','longest pass':'longComp','tackles + assists':'tackles','tackles and assists':'tackles','combined tackles':'tackles','tackles':'tackles','tackle':'tackles','solo tackles':'soloTk','solo':'soloTk','fantasy points':'fanPts','fantasy':'fanPts','fan pts':'fanPts','fp':'fanPts'},
  cmpLabels: {passYds:'Pass Yds',passTds:'Pass TDs',passAtt:'Pass Att',passComp:'Completions',passInt:'INTs',rushYds:'Rush Yds',rushAtt:'Carries',rushTds:'Rush TDs',recYds:'Rec Yds',receptions:'Receptions',recTds:'Rec TDs',rushRecYds:'Rush+Rec Yds',anytimeTd:'Anytime TD',targets:'Targets',fanPts:'Fantasy Pts',longRec:'Longest Rec',longRush:'Longest Rush',longComp:'Longest Comp',tackles:'Tackles+Ast',soloTk:'Solo Tackles'},
  teamCols: [['points','Pts'],['plays','Plays'],['passYds','PaYd'],['passAtt','PaAtt'],['passComp','Cmp'],['passTds','PaTD'],['passInt','INT'],['sacks','Sck'],['rushYds','RuYd'],['rushAtt','RuAtt'],['rushTds','RuTD'],['receptions','Rec'],['targets','Tgt']],
  viewDefaults: { sortKey:'fanPts', statsStat:'receptions', teamsSort:'points' },
  oddsMkts: [['passYds','Pass Yds'],['passTds','Pass TDs'],['passAtt','Pass Att'],['rushYds','Rush Yds'],['rushAtt','Rush Att'],['receptions','Receptions'],['recYds','Rec Yds'],['rushRecYds','Rush+Rec'],['anytimeTd','Anytime TD'],['tackles','Tackles+Ast']],
  tileOrder: ['paydirt','elite','bunnies','bogey','streak','chunk','wrap','usage','next','stack','wx','push','clamp','form'],
  posColors: {'QB':'#ef4444','RB':'#22c55e','WR':'#3b82f6','TE':'#f59e0b','LB':'#a855f7','DL':'#f97316','DB':'#06b6d4'},
  crew: [{k:'multi',n:'Multi Builder',i:'ti-stack-2',d:'Stacked legs'},
    {k:'green',n:'Green Lights',i:'ti-traffic-lights',d:'Strong OVER'},
    {k:'paydirt',n:'Tuddy Targets',i:'ti-ball-american-football',d:'Redzone royalty'},
    {k:'elite',n:'Elite Matchups',i:'ti-trophy',d:'Top v soft'},
    {k:'bunnies',n:'Divisional Bunnies',i:'ti-carrot',d:'Owns this rival'},
    {k:'death',n:'Death Riders',i:'ti-skull',d:'Strong UNDER'},
    {k:'bogey',n:'Divisional Bogey',i:'ti-mood-sad',d:'Struggles v rival'},
    {k:'streak',n:'Streakers',i:'ti-flame',d:'Hot form'},
    {k:'chunk',n:'Chunk Plays',i:'ti-bolt',d:'Big-play streaks'},
    {k:'wrap',n:'Tackle Machines',i:'ti-hammer',d:'Tackle volume'},
    {k:'wx',n:'Weather Watch',i:'ti-wind',d:'Conditions angles'},
    {k:'usage',n:'Usage Trend',i:'ti-activity',d:'Role shifts'},
    {k:'next',n:'Next Man Up',i:'ti-user-plus',d:'Injury volume'},
    {k:'stack',n:'Stack Lab',i:'ti-link',d:'Correlated SGMs'},
    {k:'push',n:'Playoff Push',i:'ti-ladder',d:'Standings pressure'},
    {k:'form',n:'Form Alerts',i:'ti-trending-up',d:'Trend shifts'},
    {k:'clamp',n:'Clamp Watch',i:'ti-lock',d:'Shadow CB risk'},
  ],
  dvMarkets: [['passYds','Pass Yds',150],['rushYds','Rush Yds',30],['recYds','Rec Yds',30],['receptions','Receptions',3],['rushAtt','Rush Att',8],['passAtt','Pass Att',24],['rushRecYds','Rush+Rec Yds',40],['tackles','Tackles+Ast',4]],
  roundWord: 'W',
  betStats: [['passYds','Pass Yds'],['rushYds','Rush Yds'],['rushAtt','Rush Att'],['receptions','Receptions'],['targets','Targets'],['passTds','Pass TDs'],['rushTds','Rush TDs']],
  dataFiles: { firsttd:'data/firsttd.json', redzone:'data/redzone.json', dbs:'data/dbs.json' },
  posOrder: ['QB','RB','WR','TE','LB','DL','DB'],
  dvpStats: [['receptions','Receptions'],['targets','Targets'],['recYds','Rec Yds'],['recTds','Rec TDs'],['rushYds','Rush Yds'],['rushAtt','Rush Att'],['rushTds','Rush TDs'],['passYds','Pass Yds'],['passAtt','Pass Att'],['passTds','Pass TDs'],['passInt','INTs'],['rushRecYds','Rush+Rec'],['anytimeTd','Anytime TD'],['fanPts','Fan Pts'],['tackles','Tackles+Ast'],['soloTk','Solo Tackles'],['defSacks','Sacks Made']],
};
